### ISSUE TITLE
Exium supports StyleSheetRuleSpread

### ISSUE THREAD

**Issue by SRNV** [SRNV/Exium#13]
```css
@const rule<rule> = {
    p {
    background: red;
  }
  color: purple;
};
div {
  ...rule;
}
```
