### ISSUE TITLE
Exium can describe a complex StylesheetSelectorList

### ISSUE THREAD

**Issue by SRNV** [SRNV/Exium#6]
```css
[attribute=""],
[attribute2],
[attribute3] element,
element.class#id,
element#id,
.class + #id,
element element2,
element[attribute],
element:hover,
element2:not(.class) {

}
```

- [x] id
- [x] classes
- [x] attributes
- [x] attributes with values
- [x] pseudo classes
  - [x] :not included
- [x] pseudo elements
- [x] + > * special characters supported
