### ISSUE TITLE
Exium can describe StylesheeSelectortPseudoElements and StylesheeSelectortPseudoClasses

### ISSUE THREAD

**Issue by SRNV** [SRNV/Exium#8]
```css
:hover {}
:not(.class) {}
::selection {
  color: white;
  background: blue;
}
```
